name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
#      - name: install GH CLI
#        run: sudo apt-get install -y gh
#      - name: Authenticate GitHub CLI
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run:
#          echo $GITHUB_TOKEN | gh auth login --with-token
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run:
          echo "PR_NUMBER=${{ github.event.pull_request.number }}"
          make eval
      # - name: Update Branch
      #   env:
      #     NAME: ${{ secrets.USER_NAME }}
      #     EMAIL: ${{ secrets.USER_EMAIL }}
      #   run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
